language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:cginternals/backports-ppa'
    packages:
      - gcc-6
      - g++-6
      - xorg-dev
      - libglu1-mesa-dev
      - libsdl2-dev
      - libx11-dev
      - libxcursor-dev
      - libglbinding-dev
      - libglbinding-dbg
      - zlib1g-dev

cache:
  directories:
    - "$HOME/.local"

install:
  -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90; fi
  -  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir cbuild && cd cbuild
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DDECAF_BUILD_TOOLS=ON ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DDECAF_BUILD_TOOLS=ON -DDECAF_GL=OFF -DDECAF_METAL=ON ..; fi
  - make -j4
